### ISSUE TITLE
Can the threat feature go over 100%?

### ISSUE THREAD

**Issue by gotex007** [Shadow-and-Light/shadow-and-light#15]
It'd be nice if we had the option to let the threat % on the nameplate go over 100%. The tooltip shows it can be tracked up to 999% and I'd like to know if I have just more aggro than the next person or if I have full threat on a mob since there's a big difference between like 110% and 400% aggro.

**Comment by gotex007** [comment]
Is it really that bad? I just know it lists it in the tooltip. It's not exact, but it shows up in multiples of 100 up to 999% once it reaches 100%. I'm not sure how it's done but it only occurs when there are multiple sources of threat like in a dungeon. I can't make it happen solo.

**Comment by gotex007** [comment]
I disabled ElvUI and tested it so I assumed it was base interface. I don't know what other addon I'd have that could do that. I tried disabling Details and DBM too an it was still there in the tooltip.

**Comment by gotex007** [comment]
I disabled all addons and it still shows in the tooltip so it must be base. I don't know.

**Comment by gotex007** [comment]
So I found out something interesting today. When treants come out and take aggro, the aggro on the nameplate already goes over 100% so it seems like it should be able to do that normally.
![VC7O9li](https://user-images.githubusercontent.com/8534139/140177370-adc7d6f5-4425-4e80-b427-55822b7edd44.png)

**Comment by Repooc** [comment]
it went over because they have more than u, soo idk

**Comment by Repooc** [comment]
Like i have mentioned, we are using the api UnitDetailedThreatSituation which returns the following
`isTanking, status, scaledPercentage, rawPercentage, threatValue = UnitDetailedThreatSituation(unit, mobUnit)` only things we use from this is status and scaledPercentage, you are prob wanting rawPercentage or threatValue.... if you want to edit the code to test and see, i may add an option or something to show them in addition to or instead of but at the moment i do not have plans to do so unless they work for you.  
if you are curious to what that stuff is [https://wowpedia.fandom.com/wiki/API_UnitDetailedThreatSituation](https://wowpedia.fandom.com/wiki/API_UnitDetailedThreatSituation)  you can reopen with ur results

**Comment by gotex007** [comment]
Okay. I really had no idea what to look at before but now I have looked at the wowpedia page and tried the other two values. 

- rawPercentage is weirdly wonky; I've had threat at 70% and not had it at 101%. Most of the time it's 255% when I have aggro so even when it doesn't feel wonky it doesn't seem any better than scaledPercentage.
- threatValue is just the raw number value which would require a lot of extra work.

So you're right. With the API how it is currently is the best we can reasonably do.
