### ISSUE TITLE
Tooltip for some information texts missing in 9.1.5

### ISSUE THREAD

**Issue by Elandril** [Shadow-and-Light/shadow-and-light#21]
**Description**
The tooltips of e.g. the S&L Guild / S&L Friends no longer show when the mouse hoovers over the texts.

**Shadow & Light Version**
4.33 from curseforge

**ElvUI Version**
12.46

**Steps to Reproduce**
1. Select one of S&L Guild / Friends as info text.

**Expected Behavior**
Show tooltip with member/friend information when the mouse hoovers over the text.

**Actual Behavior**
No tooltip visible.

**ElvUI + S&L Enabled**
Yes

**Only ElvUI Enabled**
n/a

**Additional Information**
ElvUI built-in information text show tooltips.

**Error Log**
none

**Comment by Repooc** [comment]
I can pretty say for certain you left something enabled as that has been fixed in 4.33.... As we use a library called LibQTip-1.0 which wasnt updated right away but I did a temp fix for it to function... The problem is, if an addon that has the same library in their addon, addons will use which ever one loads first and can be another addon with the broken issue.
do `/slerror on` and post a pic with ur issue as well as the `/estatus` window

**Comment by Elandril** [comment]
Yes, it seems that when updating from 4.32 to 4.33 I didn't overwrite the libs folder. Sorry, I hadn't realized that. All working now.

Many thanks!
